const data = {
  code: 200,
  msg: "성공하였습니다.",
  result: {
    mapListBanner: {
      bannerList: [],
      config: {
        isLoop: true,
        bannerExposureStartPoint: 3,
        bannerExposureGapCount: 10,
      },
    },
    roomList: [
      {
        seq: 49163815,
        id: "67bec76e032b2b12d53d0e0f",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.484733,
          lng: 126.723027,
        },
        complexName: "부평역해링턴플레이스",
        roomTitle: "2룸.최저가.냉장고.세탁기.에어컨.인덕션.넓은드레스룸.첫입주..전입불가",
        roomDesc: "고층, 59.94m², 관리비 확인 불가",
        priceTypeName: "월세",
        priceTitle: "2000/110",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/aUDSChmUmWyR9CmIyDeok",
          "https://d1774jszgerdmk.cloudfront.net/512/hkr-k68k4gjH7A8QXIS0s",
          "https://d1774jszgerdmk.cloudfront.net/512/F4Edpn9XAtixIRWnQaRUu",
          "https://d1774jszgerdmk.cloudfront.net/512/YrZKb3ojzC_6W8BfmWoQP",
          "https://d1774jszgerdmk.cloudfront.net/512/CQOMUnrRVgq4UuMcmWsgH",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52560673,
        id: "68b10d42de189d0f790ac58f",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.484733,
          lng: 126.723027,
        },
        complexName: "부평역해링턴플레이스",
        roomTitle: "전입안됨 투룸 풀옵션 첫입주 이사 아무때나",
        roomDesc: "고층, 59.94m², 관리비 확인 불가",
        priceTypeName: "월세",
        priceTitle: "2000/115",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/X9zELnzvHbxh3l3G_GwDg",
          "https://d1774jszgerdmk.cloudfront.net/512/Ao5jtE1_kIDLxSA_33sEY",
          "https://d1774jszgerdmk.cloudfront.net/512/87kjNs0NT5jXFrczxthLl",
          "https://d1774jszgerdmk.cloudfront.net/512/QjTC2uzFueDYzu6P26Bin",
          "https://d1774jszgerdmk.cloudfront.net/512/1s7OpqEos7sULBK93rjUR",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52887433,
        id: "68c9223e607f2371bc7d7cac",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.490846,
          lng: 126.722023,
        },
        complexName: "더시티뷰(생활숙박시설)",
        roomTitle: "ll 단기가능 ll 부평역1분 ll 신축 ll 허위x ll",
        roomDesc: "15층, 18.14m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "70/53",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/0yaxxxjC6w-eFa0swRhEc",
          "https://d1774jszgerdmk.cloudfront.net/512/fcMg8ck1oJ_oSa5UPNWxM",
          "https://d1774jszgerdmk.cloudfront.net/512/PZry3NMumT9Joo5Oso3K3",
          "https://d1774jszgerdmk.cloudfront.net/512/Nij7lrorSis4BQTnKGlli",
          "https://d1774jszgerdmk.cloudfront.net/512/3wH4Fb52DYw4YHASxg_dg",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52590720,
        id: "68b4676ecb5f6b3b2526d3e3",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.490846,
          lng: 126.722023,
        },
        complexName: "더시티뷰(생활숙박시설)",
        roomTitle: "oo9월업데이트o단기o풀옵션oo저렴한방oo공실24시항시대기",
        roomDesc: "7층, 18.14m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "70/53",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/Tj9f91ONUMVj5P-zgix-a",
          "https://d1774jszgerdmk.cloudfront.net/512/loMjNc0TUyDAn4ozw3bdu",
          "https://d1774jszgerdmk.cloudfront.net/512/KnpGzA-Y2cZNOsCgpTQf9",
          "https://d1774jszgerdmk.cloudfront.net/512/_SQV7ZYGID7xkZ5qFSqd-",
          "https://d1774jszgerdmk.cloudfront.net/512/4IkjxW-FsQZ1gQkkx0EDZ",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 48587837,
        id: "6794b0686cbd0f1fb454c2a3",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.484733,
          lng: 126.723027,
        },
        complexName: "부평역해링턴플레이스",
        roomTitle: "전입불가 .방2넓은거실.첫입주.풀옵션 동수역부평역도보가능대단지",
        roomDesc: "고층, 59.94m², 관리비 17만",
        priceTypeName: "월세",
        priceTitle: "2500/105",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/i7XeRBWIVnZCgiJMKmS_V",
          "https://d1774jszgerdmk.cloudfront.net/512/6E9-VaQMtBo8jrB4qvrjU",
          "https://d1774jszgerdmk.cloudfront.net/512/_wz-ca7HjQpWUNM3Sn1D5",
          "https://d1774jszgerdmk.cloudfront.net/512/2wMolBmiEyJuPUoAoDVCk",
          "https://d1774jszgerdmk.cloudfront.net/512/11wTFl1h9_2uO0xepu2Ik",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52962280,
        id: "68ced2cb1727372512bd50ec",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.490294,
          lng: 126.719119,
        },
        complexName: "e편한세상시티부평역",
        roomTitle: "LHㅣ신축오피스텔ㅣ1.5룸ㅣ빌트인풀옵션",
        roomDesc: "17층, 27.09m², 관리비 8만",
        priceTypeName: "전세",
        priceTitle: "1억5000",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/eHkyRRql_G6xeLzt_Qfgd",
          "https://d1774jszgerdmk.cloudfront.net/512/lWDOW1aSGZPI_B9ag9_SM",
          "https://d1774jszgerdmk.cloudfront.net/512/gXn3mrFAX4Yxn1MOko9oF",
          "https://d1774jszgerdmk.cloudfront.net/512/vaDSKkv2I35v6Z36RkePJ",
          "https://d1774jszgerdmk.cloudfront.net/512/DrjL93htvACRcTIKzZUYf",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 51205361,
        id: "684d61602cc8a62811f841dc",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.490846,
          lng: 126.722023,
        },
        complexName: "더시티뷰(생활숙박시설)",
        roomTitle: "부평역바로앞.단기가능. 즉시입주.풀옵션",
        roomDesc: "6층, 18.14m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "70/53",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/o387yWqFj-CxsTpp6pQxn",
          "https://d1774jszgerdmk.cloudfront.net/512/CnaT-iuFeNT8MDizWXCrY",
          "https://d1774jszgerdmk.cloudfront.net/512/HRvkpi3YpyA1TAXL9V5CS",
          "https://d1774jszgerdmk.cloudfront.net/512/Mie67AkEt92GNVXrTwSpr",
          "https://d1774jszgerdmk.cloudfront.net/512/coxDyoUUUdtWy7XmZqeir",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52563369,
        id: "68b12107d6f8c8794b7a2184",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.490846,
          lng: 126.722023,
        },
        complexName: "더시티뷰(생활숙박시설)",
        roomTitle: "++단기가능,몸만입주하세요,깔끔컨디션,가성비끝판왕,쓰리역세권,풀옵션++",
        roomDesc: "7층, 18.14m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "70/53",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/cqRnqO8CZq0WQO27_Mao5",
          "https://d1774jszgerdmk.cloudfront.net/512/ayZiWBeyGOF1DMTuox0wu",
          "https://d1774jszgerdmk.cloudfront.net/512/lhjDl0O8osCe13Jo5RDsi",
          "https://d1774jszgerdmk.cloudfront.net/512/xSywPWhm97lbJnwCBcvxy",
          "https://d1774jszgerdmk.cloudfront.net/512/1nYt4fMYYI98ujJR_RIbI",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52706669,
        id: "68bba3a27c39e13e3374876a",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.485477,
          lng: 126.719193,
        },
        complexName: "로뎀레뷰(676)",
        roomTitle: "역세권, 교통편리한 위치, 저렴한 쓰리룸 월세 매물",
        roomDesc: "중층, 67.84m², 관리비 9만",
        priceTypeName: "월세",
        priceTitle: "3000/60",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/Ssh6jicIDY2jWd49kfrG0",
          "https://d1774jszgerdmk.cloudfront.net/512/niHDt6tNOnkg7FVzPJJvB",
          "https://d1774jszgerdmk.cloudfront.net/512/5FfSG_1rqMLONlVPLzvSo",
          "https://d1774jszgerdmk.cloudfront.net/512/cgd80dWvlcG0NXDNkQQoX",
          "https://d1774jszgerdmk.cloudfront.net/512/T0-DnuDFxIg6tMvnbDIdc",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 49971879,
        id: "67f61df97f022832ac72f677",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.484733,
          lng: 126.723027,
        },
        complexName: "부평역해링턴플레이스",
        roomTitle: "귀한 전입가능.넓은2룸.즉시입주가능.보증금조정가능.풀옵션",
        roomDesc: "고층, 59.94m², 관리비 17만",
        priceTypeName: "월세",
        priceTitle: "2000/120",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/ka_cCbuH_Y737uWA3wfK7",
          "https://d1774jszgerdmk.cloudfront.net/512/lB4TSiG7ymIQjbmM4Y38D",
          "https://d1774jszgerdmk.cloudfront.net/512/5zprC2Qwrnp8geCf8NgxN",
          "https://d1774jszgerdmk.cloudfront.net/512/l8Golcbe7w1YMXBc0xx3S",
          "https://d1774jszgerdmk.cloudfront.net/512/ueaxKiyM7LBM1irlyKlu0",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52839111,
        id: "68c540a47607701b8e170fef",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.484733,
          lng: 126.723027,
        },
        complexName: "부평역해링턴플레이스",
        roomTitle: "첫입주, 1.5룸, 풀옵션, 더블역세권,보증금조절가능",
        roomDesc: "7층, 44.22m², 관리비 없음",
        priceTypeName: "월세",
        priceTitle: "1000/90",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/nak54neOsJQY6Kdg6mkk5",
          "https://d1774jszgerdmk.cloudfront.net/512/DcbXHL1YlNf0-X6AAL0sp",
          "https://d1774jszgerdmk.cloudfront.net/512/erUgR0ID3KcLvpkXNSB84",
          "https://d1774jszgerdmk.cloudfront.net/512/twe1hnttwoD2HoTwGxr4J",
          "https://d1774jszgerdmk.cloudfront.net/512/It-bdH-uv97GNOM-vcFLF",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52934157,
        id: "68ccb7f3c926c9022b101fb3",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.485292,
          lng: 126.712148,
        },
        complexName: "부평하우스토리어반그린",
        roomTitle: "백운역 도보 5분거리 신축 풀옵션 쓰리룸 숲세권",
        roomDesc: "11층, 82.29m², 관리비 9만",
        priceTypeName: "전세",
        priceTitle: "2억1000",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/etmDB2uUehEkJbuN4kRlQ",
          "https://d1774jszgerdmk.cloudfront.net/512/MGxWkpA4Awbzm8Yr8-MPd",
          "https://d1774jszgerdmk.cloudfront.net/512/UXhog059sU7HlTj8EDGGo",
          "https://d1774jszgerdmk.cloudfront.net/512/UaXhmOIJo2GCN42Fl3oQg",
          "https://d1774jszgerdmk.cloudfront.net/512/1NnV23ger37SgEp7BPBcD",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52757186,
        id: "68bfb82b1f94ff70415e80ed",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.484733,
          lng: 126.723027,
        },
        complexName: "부평역해링턴플레이스",
        roomTitle: "전세대출가능.가장넓은트룸.풀옵션.첫입주.잔금완납세대.넓은주차장",
        roomDesc: "중층, 59.94m², 관리비 17만",
        priceTypeName: "전세",
        priceTitle: "2억7000",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/B_B0FzNMxmKGupEQNjHGu",
          "https://d1774jszgerdmk.cloudfront.net/512/FMV4JxH8VVRdhImMl9FPr",
          "https://d1774jszgerdmk.cloudfront.net/512/hANyyn72q_pq_sbjGASU9",
          "https://d1774jszgerdmk.cloudfront.net/512/U1SFPmofwVhBi0zsNY9ZJ",
          "https://d1774jszgerdmk.cloudfront.net/512/S1NI93iDxAbHCTR2Ht6nK",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52691623,
        id: "68ba6ce277f8707a9ff3ded9",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.489945,
          lng: 126.726222,
        },
        complexName: "에코파인",
        roomTitle: "급매 부평역초역세권 에코파인큰평수 투자가치우수",
        roomDesc: "17층, 77.82m², 관리비 15만",
        priceTypeName: "매매",
        priceTitle: "2억9000",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/goFVLhI1h03dvdxXUPFfL",
          "https://d1774jszgerdmk.cloudfront.net/512/r43k_Q4o2oc-Iyd7rkLL9",
          "https://d1774jszgerdmk.cloudfront.net/512/JlEIDriAGZJYwZ_-jzmS3",
          "https://d1774jszgerdmk.cloudfront.net/512/nUAlyh8IxyUvIqNxZ2nx7",
          "https://d1774jszgerdmk.cloudfront.net/512/CuPkxKMqFVGr-tHy_TvOE",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52962281,
        id: "68ced2f4423859256b274b74",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.486277,
          lng: 126.714846,
        },
        complexName: "유하임",
        roomTitle: "신축투룸ㅣ빌트인풀옵션ㅣ방2,화2",
        roomDesc: "12층, 61.18m², 관리비 14만",
        priceTypeName: "월세",
        priceTitle: "1500/95",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/mnw9aB5zyv7_y0oLgm0oF",
          "https://d1774jszgerdmk.cloudfront.net/512/_E27zQtL-3cXBcEZ1UF6N",
          "https://d1774jszgerdmk.cloudfront.net/512/skC3nvW1j3k3wue2N222j",
          "https://d1774jszgerdmk.cloudfront.net/512/-niim5cDjawVCj6bsjPW8",
          "https://d1774jszgerdmk.cloudfront.net/512/L9hUj2PJvkqy12mrI6XyH",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 51827904,
        id: "6879ba485e1bff60eccce982",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.484733,
          lng: 126.723027,
        },
        complexName: "부평역해링턴플레이스",
        roomTitle: "부가세별도.사업자.즉시입주가능.에어컨 냉장고 세탁기 풀옵션 에어컨2대",
        roomDesc: "저층, 59.94m², 관리비 확인 불가",
        priceTypeName: "월세",
        priceTitle: "2000/100",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/lVlNFtcawHLWNPK7zZI2h",
          "https://d1774jszgerdmk.cloudfront.net/512/KxEp7UOUTXhLDN1WC9Ivx",
          "https://d1774jszgerdmk.cloudfront.net/512/VUu7NfUXrgYhwD0OWxFh3",
          "https://d1774jszgerdmk.cloudfront.net/512/zEnTUn2RL0WHFlQtD7BRJ",
          "https://d1774jszgerdmk.cloudfront.net/512/YB2Z9Y6FsiBTw-M8VOeau",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52740206,
        id: "68be826c9ae6731142a2bb1d",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.490846,
          lng: 126.722023,
        },
        complexName: "더시티뷰(생활숙박시설)",
        roomTitle: "부평역1분거리ㅣ개방감좋은시내뷰ㅣ준신축+풀옵션",
        roomDesc: "고층, 18.14m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "70/53",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/oP7IxRYvIHs26WKzYkq63",
          "https://d1774jszgerdmk.cloudfront.net/512/sDqyafj5hJtB2Ouwm3Phw",
          "https://d1774jszgerdmk.cloudfront.net/512/a2R7ZGY9lcDzrBjMbvj-S",
          "https://d1774jszgerdmk.cloudfront.net/512/YfxEdi-7kX2g9GjxQH_32",
          "https://d1774jszgerdmk.cloudfront.net/512/3PbpIxPYxg-I7ddxBJN5k",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52567277,
        id: "68b13e465ad4466ee5ca88fa",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.484733,
          lng: 126.723027,
        },
        complexName: "부평역해링턴플레이스",
        roomTitle: "전입안됨 신축풀옵션 즉시 이사가능",
        roomDesc: "고층, 59.94m², 관리비 없음",
        priceTypeName: "월세",
        priceTitle: "2000/120",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/A8oh2EhWpSpd7GTf9qRo7",
          "https://d1774jszgerdmk.cloudfront.net/512/FwpSnpodolVV9qXWDZA4j",
          "https://d1774jszgerdmk.cloudfront.net/512/TNiQzoMcT6h0Oeo5qrZVf",
          "https://d1774jszgerdmk.cloudfront.net/512/oFbFd-7Ob1K294K9ULLSd",
          "https://d1774jszgerdmk.cloudfront.net/512/yPU3mu8qooksfE1mqOQK5",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52507111,
        id: "68ad3587ad8ef80dbce1ab32",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.484733,
          lng: 126.723027,
        },
        complexName: "부평역해링턴플레이스",
        roomTitle: "59타입 에어컨2 대출없음 잔금완납함",
        roomDesc: "3층, 59.94m², 관리비 확인 불가",
        priceTypeName: "전세",
        priceTitle: "2억7000",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/xZbn0U0w15OUnHndgzmxE",
          "https://d1774jszgerdmk.cloudfront.net/512/vsiyu-jQj36NX3AZGqOuX",
          "https://d1774jszgerdmk.cloudfront.net/512/jkoG6B-It8PCZEXgGEdMV",
          "https://d1774jszgerdmk.cloudfront.net/512/o0UyhpVHf2CTD50KcL5vV",
          "https://d1774jszgerdmk.cloudfront.net/512/lLIqK2qLxINbqLXQ4-kf1",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52740170,
        id: "68be8233920fb80e461ede77",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.490846,
          lng: 126.722023,
        },
        complexName: "더시티뷰(생활숙박시설)",
        roomTitle: "부평역1분ㅣ깨끗한준신축ㅣ보안굿ㅣ관리잘되는집",
        roomDesc: "17층, 18.14m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "70/53",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/sd41We91DISBTbdy0F99X",
          "https://d1774jszgerdmk.cloudfront.net/512/ooXO3rNX2QWhn29NPllAJ",
          "https://d1774jszgerdmk.cloudfront.net/512/IWfgH1oucdP8fYOW7Wbs4",
          "https://d1774jszgerdmk.cloudfront.net/512/P3PDgImBa7FQfchewznK7",
          "https://d1774jszgerdmk.cloudfront.net/512/RJiQGVKcRuCNABQTthj6b",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52116511,
        id: "68906bb147c3780e00ca2112",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.490846,
          lng: 126.722023,
        },
        complexName: "더시티뷰(생활숙박시설)",
        roomTitle: "NEW부평역1분, 단기가능, 즉시입주가능",
        roomDesc: "중층, 18.14m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "70/53",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/8a7gkfAEfU3BeRcKFqGTX",
          "https://d1774jszgerdmk.cloudfront.net/512/GUmLLreUPomcabKtUwoCK",
          "https://d1774jszgerdmk.cloudfront.net/512/oALn4724j-gLnF0JUJ4M6",
          "https://d1774jszgerdmk.cloudfront.net/512/r2UzWHI0Xk_lt-cejObim",
          "https://d1774jszgerdmk.cloudfront.net/512/5BFb6Yz2xCaM-oeSVJkQw",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52977835,
        id: "68d0c5860f4289735900843d",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.490903,
          lng: 126.719182,
        },
        complexName: "아이홈(534-82)",
        roomTitle: "전화부재시 매물번호 문자주세요 ㅁ 반려동물 가능 ㅁ 즉시입주",
        roomDesc: "15층, 77.99m², 관리비 8만",
        priceTypeName: "월세",
        priceTitle: "100/80",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/DPOJTvTVfuJikbPqf9ZbP",
          "https://d1774jszgerdmk.cloudfront.net/512/EG8X_aeuMUZwfZb7Pbtm5",
          "https://d1774jszgerdmk.cloudfront.net/512/ERvYFbUPQa_rwq56ZCciy",
          "https://d1774jszgerdmk.cloudfront.net/512/zmfzSWhdY8aEs8dREbiO0",
          "https://d1774jszgerdmk.cloudfront.net/512/XBUaCSRARkRHEHcZkghKR",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52573311,
        id: "68b1840dd6b5f111b5a1717c",
        roomTypeName: "오피스텔",
        randomLocation: {
          lat: 37.490294,
          lng: 126.719119,
        },
        complexName: "e편한세상시티부평역",
        roomTitle: "이편한시티,부평역,1.5룸,주차100,즉시입주,보증금조절가능",
        roomDesc: "10층, 27.09m², 관리비 6만",
        priceTypeName: "월세",
        priceTitle: "500/75",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/1pra1toK8GONTbFnDV3it",
          "https://d1774jszgerdmk.cloudfront.net/512/aWzZC8DI4yw1ZL9ksgpYm",
          "https://d1774jszgerdmk.cloudfront.net/512/-ysr0izveX1RPKGO7jtuY",
          "https://d1774jszgerdmk.cloudfront.net/512/c6oy1vNeD6MdMKDMgrDIT",
          "https://d1774jszgerdmk.cloudfront.net/512/iQQZvI05omfF5Epc_pMR_",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
      {
        seq: 52887435,
        id: "68c922401f691370b6cffe6d",
        roomTypeName: "오피스텔 • 단기",
        randomLocation: {
          lat: 37.490846,
          lng: 126.722023,
        },
        complexName: "더시티뷰(생활숙박시설)",
        roomTitle: "ll 단기가능 ll 가성비최고 ll 신축 ll 즉시입주가능 ll",
        roomDesc: "10층, 18.14m², 관리비 7만",
        priceTypeName: "월세",
        priceTitle: "70/53",
        imgUrlList: [
          "https://d1774jszgerdmk.cloudfront.net/512/-KOkVRpU1cTWtFx6jXbGs",
          "https://d1774jszgerdmk.cloudfront.net/512/q8uDHMKsNaR783f5xkl9p",
          "https://d1774jszgerdmk.cloudfront.net/512/9LWTUVaQmzJATTmhBhrQw",
          "https://d1774jszgerdmk.cloudfront.net/512/0dY8LyR3zUYgwTOO4oOPh",
          "https://d1774jszgerdmk.cloudfront.net/512/-HxZCoUd2ISWoZjLh9gAY",
        ],
        isExtendUI: true,
        isFavorite: false,
        isPano: false,
        isQuick: true,
        isDirect: false,
        isOwner: false,
        isOwnerAuth: false,
        isMyHome: false,
        isNaverVerify: false,
        formatNaverVerifyDate: null,
        isIconFocus: false,
        iconFocusType: null,
        gid: 9040,
        dongName: "부평동",
      },
    ],
    premiumList: [
      {
        roomList: [
          {
            seq: 52495934,
            id: "68ac2d103056ca4357bcebe0",
            roomTypeName: "오피스텔",
            randomLocation: {
              lat: 37.489945,
              lng: 126.726222,
            },
            complexName: "에코파인",
            roomTitle: "부평역 도보3분, 고퀄리티, 최강 럭셔리한 신축 오피스텔",
            roomDesc: "16층, 21.51m², 관리비 5만",
            priceTypeName: "월세",
            priceTitle: "500/54",
            imgUrlList: [
              "https://d1774jszgerdmk.cloudfront.net/512/2b19f9fc-3b1e-4612-ac09-c009a24eba17",
              "https://d1774jszgerdmk.cloudfront.net/512/61239522-0026-46d2-9d99-dde9be6c8a63",
              "https://d1774jszgerdmk.cloudfront.net/512/313ce124-1d72-4d7e-8019-115409607a03",
              "https://d1774jszgerdmk.cloudfront.net/512/7b2ab6a6-2e9f-4085-92a7-fc2a757d0d20",
              "https://d1774jszgerdmk.cloudfront.net/512/a3e42c49-8457-45cd-be3d-e69e0f31daf7",
            ],
            isFavorite: false,
            isPano: false,
            isIconFocus: false,
            iconFocusType: null,
            gid: 9040,
            dongName: "부평동",
          },
        ],
        agent: {
          id: "54cdd69ce4b06e91bf0ea877",
          name: "CoCo공인중개사사무소",
          profileUrl: "https://d2bqvyba2nre74.cloudfront.net/d850600dafd0a59d236b284fe611f1f9",
          activeRoomCount: 73,
          since: "2015.02.01",
        },
      },
      {
        roomList: [
          {
            seq: 52573311,
            id: "68b1840dd6b5f111b5a1717c",
            roomTypeName: "오피스텔",
            randomLocation: {
              lat: 37.490294,
              lng: 126.719119,
            },
            complexName: "e편한세상시티부평역",
            roomTitle: "이편한시티,부평역,1.5룸,주차100,즉시입주,보증금조절가능",
            roomDesc: "10층, 27.09m², 관리비 6만",
            priceTypeName: "월세",
            priceTitle: "500/75",
            imgUrlList: [
              "https://d1774jszgerdmk.cloudfront.net/512/1pra1toK8GONTbFnDV3it",
              "https://d1774jszgerdmk.cloudfront.net/512/aWzZC8DI4yw1ZL9ksgpYm",
              "https://d1774jszgerdmk.cloudfront.net/512/-ysr0izveX1RPKGO7jtuY",
              "https://d1774jszgerdmk.cloudfront.net/512/c6oy1vNeD6MdMKDMgrDIT",
              "https://d1774jszgerdmk.cloudfront.net/512/iQQZvI05omfF5Epc_pMR_",
            ],
            isFavorite: false,
            isPano: false,
            isIconFocus: false,
            iconFocusType: null,
            gid: 9040,
            dongName: "부평동",
          },
          {
            seq: 51205361,
            id: "684d61602cc8a62811f841dc",
            roomTypeName: "오피스텔",
            randomLocation: {
              lat: 37.490846,
              lng: 126.722023,
            },
            complexName: "더시티뷰(생활숙박시설)",
            roomTitle: "부평역바로앞.단기가능. 즉시입주.풀옵션",
            roomDesc: "6층, 18.14m², 관리비 7만",
            priceTypeName: "월세",
            priceTitle: "70/53",
            imgUrlList: [
              "https://d1774jszgerdmk.cloudfront.net/512/o387yWqFj-CxsTpp6pQxn",
              "https://d1774jszgerdmk.cloudfront.net/512/CnaT-iuFeNT8MDizWXCrY",
              "https://d1774jszgerdmk.cloudfront.net/512/HRvkpi3YpyA1TAXL9V5CS",
              "https://d1774jszgerdmk.cloudfront.net/512/Mie67AkEt92GNVXrTwSpr",
              "https://d1774jszgerdmk.cloudfront.net/512/coxDyoUUUdtWy7XmZqeir",
            ],
            isFavorite: false,
            isPano: false,
            isIconFocus: false,
            iconFocusType: null,
            gid: 9040,
            dongName: "부평동",
          },
        ],
        agent: {
          id: "66261d06e2ca4775ea793702",
          name: "원공인중개사사무소",
          profileUrl: "https://d2bqvyba2nre74.cloudfront.net/175723c6209fdccab88dc9014a308be1",
          activeRoomCount: 18,
          since: "2024.04.22",
        },
      },
    ],
    region: null,
    total: 69,
    limit: 24,
    hasMore: true,
    page: 1,
  },
  responseTime: "2025-09-23 09:48:09",
};

const section = document.createElement("section");
section.style.display = "grid";
section.style.gridTemplateColumns = `repeat(3, 1fr)`;

document.body.appendChild(section);

data.result.roomList.forEach((v) => {
  const article = document.createElement("article");
  article.style.display = "flex";
  article.style.alignItems = "center";
  article.style.gap = "10px";
  article.style.borderRadius = "15px";
  article.style.border = "3px solid black";
  article.style.cursor = "pointer";
  section.appendChild(article);

  const img = document.createElement("img");
  img.src = v.imgUrlList[0];
  img.style.width = "30%";
  img.style.height = "100%";
  img.style.borderRadius = "15px";
  img.style.objectFit = "cover";
  article.appendChild(img);

  const div = document.createElement("div");
  div.style.display = "flex";
  div.style.flexDirection = "column";
  article.appendChild(div);

  const h3 = document.createElement("h3");
  h3.innerText = v.priceTitle;
  div.appendChild(h3);

  const p1 = document.createElement("p");
  p1.innerText = `${v.roomTypeName} ${v.complexName}`;
  div.appendChild(p1);

  const p2 = document.createElement("p");
  p2.innerText = v.roomDesc;
  div.appendChild(p2);

  const p3 = document.createElement("p");
  p3.innerText = v.roomTitle;
  div.appendChild(p3);
});
